name: shopit
description: Flutter ecommerce app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.2.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: 2.4.9
  riverpod_annotation: 2.3.3
  go_router: 13.0.1
  google_fonts: 6.1.0
  flutter_svg: 2.0.9
  firebase_core: 2.23.0
  cloud_firestore: 4.13.2
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  firebase_auth: 4.14.1
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  path_provider: 2.1.1
  shimmer: 3.0.0
  flutter_slidable: 3.0.1
  cached_network_image: 3.3.0
  firebase_crashlytics: 3.4.5
  mocktail: 1.0.1
  supabase_flutter: 2.0.1
  firebase_storage: 11.5.2
  image_picker: 1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  custom_lint: 0.5.7
  riverpod_lint: 2.3.7
  build_runner: 2.4.6
  riverpod_generator: 2.3.9
  freezed: 2.4.5
  json_serializable: 6.7.1
  isar_generator: 3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/l10n/