name: shopit
description: Flutter ecommerce app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.4.0-250.0.dev'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: 2.4.9
  riverpod_annotation: 2.3.3
  go_router: 13.0.1
  google_fonts: 6.1.0
  flutter_svg: 2.0.9
  firebase_core: 2.24.2
  cloud_firestore: 4.14.0
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  firebase_auth: 4.16.0
  path_provider: 2.1.2
  shimmer: 3.0.0
  flutter_slidable: 3.0.1
  cached_network_image: 3.3.1
  firebase_crashlytics: 3.4.9
  mocktail: 1.0.2
  supabase_flutter: 2.2.0
  firebase_storage: 11.6.0
  image_picker: 1.0.7
  drift: 2.14.1
  sqlite3_flutter_libs: 0.5.19+1
  path: 1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  custom_lint: 0.5.8
  riverpod_lint: 2.3.7
  build_runner: 2.4.8
  riverpod_generator: 2.3.9
  freezed: 2.4.6
  json_serializable: 6.7.1
  drift_dev: 2.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/l10n/