name: shopit
description: Flutter ecommerce app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.4.0-190.1.beta'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  go_router: 13.2.1
  google_fonts: 6.2.1
  flutter_svg: 2.0.10+1
  firebase_core: 2.27.1
  cloud_firestore: 4.15.9
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  firebase_auth: 5.5.1
  path_provider: 2.1.2
  shimmer: 3.0.0
  flutter_slidable: 3.1.0
  cached_network_image: 3.3.1
  firebase_crashlytics: 3.4.19
  mocktail: 1.0.3
  supabase_flutter: 2.3.4
  firebase_storage: 11.6.10
  image_picker: 1.0.7
  drift: 2.16.0
  sqlite3_flutter_libs: 0.5.20
  path: 1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  custom_lint: 0.6.4
  riverpod_lint: 2.3.10
  build_runner: 2.4.8
  riverpod_generator: 2.4.0
  freezed: 2.4.7
  json_serializable: 6.7.1
  drift_dev: 2.16.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/l10n/