name: shopit
description: Flutter ecommerce app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.1.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: 2.4.0
  riverpod_annotation: 2.1.5
  go_router: 10.1.2
  google_fonts: 6.0.0
  flutter_svg: 2.0.7
  firebase_core: 2.15.1
  cloud_firestore: 4.9.1
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  firebase_auth: 4.9.0
  smooth_page_indicator: 1.1.0
  carousel_slider: 4.2.1
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  path_provider: 2.1.1
  shimmer: 3.0.0
  flutter_slidable: 3.0.0
  cached_network_image: 3.2.3
  firebase_crashlytics: 3.3.5
  mocktail: 1.0.0
  supabase_flutter: 1.10.16
  firebase_storage: 11.2.6
  image_picker: 1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  custom_lint: 0.5.3
  riverpod_lint: 2.1.0
  build_runner: 2.4.6
  riverpod_generator: 2.3.2
  freezed: 2.4.2
  json_serializable: 6.7.1
  isar_generator: 3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/l10n/