name: shopit
description: Flutter ecommerce app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  go_router: 13.2.5
  google_fonts: 6.2.1
  flutter_svg: 2.0.17
  firebase_core: 2.32.0
  cloud_firestore: 4.17.5
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  firebase_auth: 4.20.0
  path_provider: 2.1.5
  shimmer: 3.0.0
  flutter_slidable: 3.1.2
  cached_network_image: 3.4.1
  firebase_crashlytics: 3.5.7
  mocktail: 1.0.4
  supabase_flutter: 2.8.4
  firebase_storage: 11.7.7
  image_picker: 1.1.2
  drift: 2.25.1
  sqlite3_flutter_libs: 0.5.31
  path: 1.9.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  custom_lint: 0.7.3
  riverpod_lint: 2.6.4
  build_runner: 2.4.15
  riverpod_generator: 2.6.4
  freezed: 2.5.8
  json_serializable: 6.9.4
  drift_dev: 2.25.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/l10n/